# Generated by Django 4.2.30 on 2026-05-14 13:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Data Transazione')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importo Versato')),
                ('description', models.TextField(blank=True, verbose_name='Causale')),
                ('transaction_type', models.CharField(choices=[('VERSAMENTO', 'Versamento Contanti'), ('ESTRATTO_CONTO', 'Movimento Estratto Conto')], max_length=20, verbose_name='Tipo Transazione')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Transazione Bancaria',
                'verbose_name_plural': 'Transazioni Bancarie',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CashClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Data Chiusura')),
                ('operator', models.CharField(max_length=100, verbose_name='Operatore')),
                ('total_in', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totale Incassato')),
                ('total_out', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Totale Uscite')),
                ('calculated_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Calcolato')),
                ('image_ref', models.ImageField(blank=True, null=True, upload_to='closures/%Y/%m/', verbose_name='Immagine di Riferimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chiusura Cassa',
                'verbose_name_plural': 'Chiusure Cassa',
                'ordering': ['-date'],
            },
        ),
    ]
