# Generated by Django 4.2.30 on 2026-05-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashclosure',
            name='calculated_balance',
        ),
        migrations.RemoveField(
            model_name='cashclosure',
            name='total_in',
        ),
        migrations.RemoveField(
            model_name='cashclosure',
            name='total_out',
        ),
        migrations.AddField(
            model_name='cashclosure',
            name='cassa_auto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cassa Auto'),
        ),
        migrations.AddField(
            model_name='cashclosure',
            name='contanti',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Contanti'),
        ),
        migrations.AddField(
            model_name='cashclosure',
            name='distrib',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Distrib.'),
        ),
        migrations.AddField(
            model_name='cashclosure',
            name='pag_pos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Pag.Pos'),
        ),
        migrations.AddField(
            model_name='cashclosure',
            name='reso_auto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Reso Auto'),
        ),
        migrations.AddField(
            model_name='cashclosure',
            name='reso_cont',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Reso Cont.'),
        ),
        migrations.AddField(
            model_name='cashclosure',
            name='totale_generale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='TOTALE'),
        ),
        migrations.CreateModel(
            name='CashClosureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=150, verbose_name='Descrizione Reparto')),
                ('incomes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Entrate')),
                ('expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Uscite')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Cassa')),
                ('closure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reconciliation.cashclosure', verbose_name='Chiusura Cassa')),
            ],
            options={
                'verbose_name': 'Voce Chiusura',
                'verbose_name_plural': 'Voci Chiusura',
            },
        ),
    ]
